hardened tests

diff --git a/src/git-conveyor-sync b/src/git-conveyor-sync
--- a/src/git-conveyor-sync
+++ b/src/git-conveyor-sync
@@ -38,9 +38,9 @@ resource_do() {
 
 	# Else, let's attempt the clone.
 	if [ x"$LOCAL_DIR" == x"" ];then
-	    git clone --quiet $REMOTE_URL
+	    do_clone $REMOTE_URL || (echo "ERROR: Could not clone $REMOTE_URL." >&2; exit 2)
 	else
-	    git clone --quiet $REMOTE_URL $LOCAL_DIR
+	    do_clone $REMOTE_URL $LOCAL_DIR || (echo "ERROR: Could not clone $REMOTE_URL to $LOCAL_DIR." >&2; exit 2)
 	fi
     elif [ $# -eq 0 ]; then
 	# With no arguments, we are updating the current repository. Make sure
