partial implementation; need to jump off and improve testing; move away from standing repos, create repo or test, delete that repo when done

diff --git a/src/git-conveyor-status b/src/git-conveyor-status
--- a/src/git-conveyor-status
+++ b/src/git-conveyor-status
@@ -20,14 +20,12 @@ resource_do() {
     if is_github_clone; then
 	if is_github_configured; then
 	    # We are good for connection check.
-	    local USER_JSON=`curl -s -u $GITHUB_AUTH_TOKEN:x-oauth-basic https://api.github.com/user`
-	    local RESULT=$?
-	    if [ $RESULT -ne 0 ]; then
-		echo "Could not connect with GitHub (or token invalid)." >&2
-	    else
-		local PHP_BIN=$DFS_HOME/third-party/php5/runnable/bin/php
-		local GITHUB_LOGIN=`echo $USER_JSON | $PHP_BIN -r '$handle = fopen ("php://stdin","r"); $json = stream_get_contents($handle); $data = json_decode($json, true); print $data["login"];'`
+	    source $GIT_CONVEY_DIR/lib/github-hooks.sh
+	    local GITHUB_LOGIN=`get_login`
+	    if [ x"$GITHUB_LOGIN" -ne x"" ]; then
 		echo "Connected to GitHub as: $GITHUB_LOGIN"
+	    else
+		echo "Could not connect with GitHub (or token invalid)." >&2
 	    fi
 	fi # if_github_configured
     fi # if is_github_clone
